name: build_test_Ubuntu-22.04

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
    - uses: actions/checkout@v3
    - name: googletest
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ..
        make
        cd ../../tests/cpp
        cp -r ../../googletest/googletest/include/gtest .
        cp -r ../../googletest/build/lib/* .
    - name: eigen
      run: |
        sudo apt install libeigen3-dev
    - name: nlohmann-json3-dev
      run: |
        sudo apt install nlohmann-json3-dev
    - name: nlohmann-json3-dev
      run: |
        sudo apt install graphviz
    - name: nanobind
      run: |
        pip install nanobind
    - name: build_test
      run: |
        echo $GITHUB_WORKSPACE
        pwd
        mkdir -p ~/lib ~/include/sharqit
        export LD_LIBRARY_PATH="${GITHUB_WORKSPACE}/lib:$LD_LIBRARY_PATH"
        cd sharqit/cpp
        make
        make install
        ls ~/lib
        ls ~/include/sharqit
        cd ../../tests/cpp
        cp ../../sharqit/cpp/libshrqt.so .
        ls -al
        make
        ./test_sharqit
    - name: build_test_py
      run: |
        python3 setup.py install --user
        cd tests/py
        ./test.sh
